apiVersion: v1
kind: Service
metadata:
  name: btcwallet-ui-service
spec:
  selector:
    app: btcwallet-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 8083
  type: NodePort
